# Generated by Django 4.1.2 on 2022-10-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('image', models.ImageField(upload_to='media/')),
                ('price', models.IntegerField()),
                ('price_value', models.CharField(choices=[('$', '$'), ('Euro', 'Euro')], default='$', max_length=50)),
                ('doors', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('trans', models.CharField(choices=[('None', 'None'), ('Mechanic', 'Mechanic'), ('Automatic', 'Automatic'), ('AI', 'AI')], default='None', max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_from', models.CharField(max_length=221)),
                ('where_to', models.CharField(max_length=221)),
                ('go_date', models.DateTimeField()),
                ('back_date', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
            ],
        ),
    ]
